[package]
name = "activity_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
windows = { version = "0.59.0", features = ["Win32_System_SystemInformation", "Win32_UI_Input_KeyboardAndMouse"] }
chrono = "0.4"
